git:
    submodules: true

matrix:
    include:
      - os: linux
        language: generic
        python: "3.7"
        sudo: required
        dist: xenial
        services:
          - xvfb
        before_install:
          - sudo apt-get install -y python3-pip libgl1-mesa-glx libnss3 libxcomposite-dev libxcursor-dev libxi6 libxtst6 libasound2 libegl1-mesa libxkbcommon-x11-0
          - export QT_QPA_PLATFORM=offscreen
        before_deploy:
          - ./scripts/generate_deb_files.sh
          - export FILE=ZeronetBrowser_${TRAVIS_TAG}_i386.deb
          - mv dist/ZeronetBrowser pkg-debian/usr/share/
          - dpkg -b pkg-debian/ $FILE
      - os: osx
        language: generic
        env: TOXENV=py37
        sudo: true
        before_deploy:
          - nvm install --lts
          - nvm use --lts
          - npm install -g create-dmg
          - export FILE=ZeronetBrowser_${TRAVIS_TAG}.dmg
          - create-dmg 'ZeronetBrowser.app' || true
          - mv ZeronetBrowser\ ${TRAVIS_TAG/v}.dmg $FILE

install:
  - pip3 install setuptools
  - cd ./ZeroNet
  - pip3 install -r requirements.txt
  - cd ..
  - pip3 install pyinstaller PyQt5-sip PyQt5 PyQtWebEngine
script:
  - python3 test.py
  - pyinstaller --windowed browser.spec

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - $FILE
  on:
    tags: true
