git:
    submodules: true

matrix:
    include:
      - os: linux
        language: generic
        python: "2.7"
        sudo: required
        dist: xenial
        before_install:
          - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.2-xenial
          - sudo apt-get update
          - sudo apt-get install -y msgpack-python python-gevent python-dev build-essential libgl1-mesa-dev qt511-meta-minimal qt511webengine qt511svg
          - sudo chmod +x /opt/qt511/bin/qt511-env.sh
          - /opt/qt511/bin/qt511-env.sh
          - chmod +x get-pyqt5-linux.sh
          - ./get-pyqt5-linux.sh
        after_success:
          - cp ./dist/ZeronetBrowser/PyQt5/Qt/resources/* ./dist/ZeronetBrowser/PyQt5/Qt/libexec/
          - cp -r ./dist/ZeronetBrowser/PyQt5/Qt/translations/qtwebengine_locales/ ./dist/ZeronetBrowser/PyQt5/Qt/libexec/
      - os: osx
        language: generic
        sudo: true
        before_install:
          - pip install msgpack gevent enum34
          - brew install qt5
          - sudo /usr/libexec/locate.updatedb
          - locate qt5
          - chmod +x ./get-pyqt5-osx.sh
          - ./get-pyqt5-osx.sh

install:
  - sudo pip install pyinstaller cffi
  - sudo pip install --upgrade setuptools
  - echo "import zeronet" > ZeroNet/__init__.py
script:
  - python test.py
  - pyinstaller browser.spec

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/ZeronetBrowser
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
