language: generic
matrix:
    include:
      - os: linux
        dist: trusty
        sudo: true
        addons:
          apt:
            update: true
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - python-setuptools
              - python-gevent
              - python-greenlet
              - python-minimal
              - python-msgpack
              - python-wheel
      - os: osx
        sudo: true

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install pyinstaller; else pip install --user pyinstaller; fi
  - sudo pip install six
  - echo "import zeronet" > ZeroNet/src/__init__.py
script:
  - pyinstaller browser.spec

before_deploy:
  - zip build-$TRAVIS_OS_NAME.zip dist/ZeronetBrowser
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
