git:
    submodules: true

matrix:
    include:
      - os: linux
        language: python
        python: "2.7"
        sudo: required
        dist: xenial
        virtualenv:
          system_site_packages: true
        before_install:
          - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-xenial
          - sudo apt-get update
          - sudo apt-get install -y msgpack-python python-gevent python-dev build-essential libgl1-mesa-dev qt510-meta-full
          - chmod +x get-pyqt5-linux.sh
          - ./get-pyqt5-linux.sh
      - os: osx
        language: generic
        sudo: true
        before_install:
          - brew install sip --without-python
          - travis_wait 30 brew install pyqt5 --without-python
          - pip install msgpack gevent

install:
  - sudo pip install pyinstaller pyinstaller-hooks
  - sudo pip install --upgrade setuptools
  - echo "import zeronet" > ZeroNet/src/__init__.py
script:
  - python test.py
  - pyinstaller browser.spec

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/ZeronetBrowser
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
