git:
    submodules: true

matrix:
    include:
      - os: linux
        language: generic
        python: "2.7"
        sudo: required
        dist: xenial
        services:
          - xvfb
        before_install:
          - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.0-xenial
          - sudo apt-get update
          - sudo apt-get install -y msgpack-python python-gevent python-dev build-essential libgl1-mesa-dev qt512-meta-minimal qt512webengine qt512svg
          - sudo chmod +x /opt/qt512/bin/qt512-env.sh
          - /opt/qt512/bin/qt512-env.sh
          - chmod +x get-pyqt5-linux.sh
          - ./get-pyqt5-linux.sh
          - printenv
          - export LD_LIBRARY_PATH=/opt/qt512/lib:/opt/qt512/plugins/platforms
      - os: osx
        language: generic
        sudo: true
        before_install:
          - pip install msgpack gevent enum34
          - brew install qt5
          - sudo /usr/libexec/locate.updatedb
          - locate qt5
          - chmod +x ./get-pyqt5-osx.sh
          - ./get-pyqt5-osx.sh
          - export DYLD_LIBRARY_PATH=/usr/local/opt/qt5/lib

install:
  - sudo pip install pyinstaller cffi
  - sudo pip install --upgrade setuptools
  - echo "import zeronet" > ZeroNet/__init__.py
script:
  - python test.py
  - pyinstaller browser.spec

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/ZeronetBrowser
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
