git:
    submodules: true

matrix:
    include:
      - os: linux
        language: generic
        python: "2.7"
        sudo: required
        dist: xenial
        services:
          - xvfb
        before_install:
          - sudo apt-get install -y python3-pip libgl1-mesa-glx libnss3 libxcomposite-dev libxcursor-dev libxi6 libxtst6 libasound2 libegl1-mesa libxkbcommon-x11-0
          - export QT_QPA_PLATFORM=offscreen
      - os: osx
        language: generic
        sudo: true

install:
  - pip3 install setuptools
  - cd ./ZeroNet
  - pip3 install -r requirements.txt
  - cd ..
  - pip3 install pyinstaller PyQt5-sip PyQt5 PyQtWebEngine
script:
  - python3 test.py
  - pyinstaller browser.spec

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/ZeronetBrowser
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
