matrix:
    include:
      - os: linux
        language: python
        dist: trusty
        sudo: true
      - os: osx
        language: generic
        sudo: true

install:
  - sudo pip install pyinstaller
  - sudo pip install --upgrade setuptools
  - echo "import zeronet" > ZeroNet/src/__init__.py
script:
  - pyinstaller browser.spec

before_deploy:
  - zip build-$TRAVIS_OS_NAME.zip dist/ZeronetBrowser
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
