platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

build: off

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip setuptools
  - python -m pip install pyinstaller pyinstaller-hooks msgpack gevent

install:
  - curl -LO https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.13/sip-4.19.13.zip
  - dir
  - 7z x sip-4.19.13.zip -osip-4.19.13
  - dir
  - cd sip-4.19.13 && python configure.py && make && make install
  - curl -LO https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.11.3/PyQt5_gpl-5.11.3.zip
  - 7z x PyQt5_gpl-5.11.3.zip -oPyQt5_gpl-5.11.3
  - cd PyQt5_gpl-5.11.3
  - python configure.py
  - make
  - make install
  - cd ..
  - echo "import zeronet" > ZeroNet/src/__init__.py


test_script:
- python test.py
