platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

build: off

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip setuptools
  - python -m pip install pyinstaller pyinstaller-hooks msgpack gevent

install:
  - C:\Miniconda install pyqt5
  - echo "import zeronet" > ZeroNet/src/__init__.py


test_script:
- python test.py
