platform:
  - x64

image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

artifacts:
  - path: build-windows.zip

build: off

init:
  - cmd: copy C:\windows\system32\libeay32.dll C:\Qt\5.12\msvc2017_64\bin
  - cmd: copy C:\windows\system32\ssleay32.dll C:\Qt\5.12\msvc2017_64\bin
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;C:\Qt\5.12\msvc2017_64\bin;%PATH%
  - python -m pip install --upgrade pip
  - python -m pip install pyinstaller msgpack gevent pypiwin32 PyQt5-sip PyQt5 PyQtWebEngine

install:
  - git submodule update --init --recursive
  - cd ZeroNet
  - python -m pip install -r requirements.txt
  - cd ..

test_script:
  - python test.py
  - pyinstaller browser.spec

after_test:
  #- copy .\dist\ZeronetBrowser\PyQt5\Qt\resources\* .\dist\ZeronetBrowser\PyQt5\Qt\bin\
  #- copy .\dist\ZeronetBrowser\PyQt5\Qt\translations\qtwebengine_locales\ .\dist\ZeronetBrowser\PyQt5\Qt\bin\
  - 7z a build-windows.zip dist/ZeronetBrowser/*

deploy:
  provider: GitHub
  auth_token:
    secure: 6eX2olaIxe4TsfETod+SYOyDsIKwmDivjirb7RPvl/Zd4zYW3dzGr4MieJ2BP89P # your encrypted token from GitHub
  artifact: build-windows.zip
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
