platform:
  - x64

image: Visual Studio 2017

environment:
  - PYTHON: "C:\\Python27-x64"
  - MINGW: "C:\\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1"

build: off

init:
  - "SET PATH=%MINGW%;%MINGW%\\mingw64\\bin;%PATH%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip setuptools
  - python -m pip install pyinstaller pyinstaller-hooks msgpack gevent

install:
  - curl -LO https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.13/sip-4.19.13.zip
  - dir
  - 7z x sip-4.19.13.zip
  - dir
  - cd sip-4.19.13
  - python configure.py
  - dir
  - nmake
  - nmake install
  - cd ..
  - curl -LO https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.11.3/PyQt5_gpl-5.11.3.zip
  - 7z x PyQt5_gpl-5.11.3.zip
  - cd PyQt5_gpl-5.11.3
  - python configure.py
  - nmake
  - nmake install
  - cd ..
  - echo "import zeronet" > ZeroNet/src/__init__.py


test_script:
- python test.py
