platform:
  - x64

image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PATH: C:\Program Files (x86)\NSIS\;%PATH%

artifacts:
  - path: ZeronetBrowser_%APPVEYOR_REPO_TAG_NAME%_setup.exe

build: off

init:
  - cmd: copy C:\windows\system32\libeay32.dll C:\Qt\5.12\msvc2017_64\bin
  - cmd: copy C:\windows\system32\ssleay32.dll C:\Qt\5.12\msvc2017_64\bin
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;C:\Qt\5.12\msvc2017_64\bin;%PATH%
  - python -m pip install --upgrade pip
  - python -m pip install pyinstaller msgpack gevent pypiwin32 PyQt5-sip PyQt5 PyQtWebEngine

install:
  - git submodule update --init --recursive
  - cd ZeroNet
  - python -m pip install -r requirements.txt
  - cd ..

test_script:
  - python test.py
  - pyinstaller browser.spec

before_deploy:
  #- copy .\dist\ZeronetBrowser\PyQt5\Qt\resources\* .\dist\ZeronetBrowser\PyQt5\Qt\bin\
  #- copy .\dist\ZeronetBrowser\PyQt5\Qt\translations\qtwebengine_locales\ .\dist\ZeronetBrowser\PyQt5\Qt\bin\
  #- 7z a build-windows.zip dist/ZeronetBrowser/*
  - ps: $size = [math]::floor((Get-ChildItem dist\ -Recurse | Measure-Object -Sum Length | Select-Object -ExpandProperty Sum)/1000)
  - ps: $tag = $env:APPVEYOR_REPO_TAG_NAME
  - ps: $major, $minor, $build = $tag.substring(1).split(".")
  - makensis.exe /DTAG=%APPVEYOR_REPO_TAG_NAME% /DSIZE=$size /DMAJOR=$major /DMINOR=$minor /DBUILD=$build zeronetbrowser.nsi

deploy:
  provider: GitHub
  auth_token:
    secure: 6eX2olaIxe4TsfETod+SYOyDsIKwmDivjirb7RPvl/Zd4zYW3dzGr4MieJ2BP89P # your encrypted token from GitHub
  artifact: ZeronetBrowser_%APPVEYOR_REPO_TAG_NAME%_setup.exe
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
